services:
  api:
    build: .
    container_name: bali-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./bali.db:/app/bali.db
  

  api-dev:
    build: .
    container_name: bali-api-dev
    ports:
      - "8001:8000"
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./bali.db:/app/bali.db